export const RESOURCE = {
  AUTH: 'oauth2',
  ES: 'es',
  LOCATION_TAGS: 'locationTags',
  ONBOARDING: 'onboardinghelper',
  PERMISSION: 'permission',
  REPORTS: 'reports',
  SCHEMA: 'schema',
  SUPPLIER: 'devicesuppliers',
  SYSTEM_PERMISSION: 'syspermissionTree',
  TAG: 'tags',
  THING: 'things',
  THING_IF: 'thing-if',
  TRIGGER: 'triggers',
  TYPE: 'thingstypes',
  USER: 'users',
  USER_GROUP: 'usergroup',
  USER_MANAGER: 'usermanager',
  USER_SYNC: 'usersync'
};
