export class Client {
  accessTokenValiditySeconds?: number = 3600;
  allowIntrospection: boolean = true;
  applicationType?: any;
  authorities?: any[];
  claimsRedirectUris?: any[];
  clearAccessTokensOnRefresh?: boolean;
  clientDescription?: string;
  clientId?: string;
  clientName?: string;
  clientSecret?: string;
  clientUri?: string;
  contacts?: string[];
  createdAt?: Date;
  defaultACRvalues?: any[];
  defaultMaxAge?: any;
  dynamicallyRegistered?: boolean;
  grantTypes: string[] = [];
  id?: number;
  idTokenEncryptedResponseAlg?: any;
  idTokenEncryptedResponseEnc?: any;
  idTokenSignedResponseAlg?: any;
  idTokenValiditySeconds?: number = 600;
  initiateLoginUri?: any;
  jwks?: any;
  jwksUri?: string;
  logoUri?: any;
  policyUri?: any;
  postLogoutRedirectUris?: any[];
  redirectUris?: string[];
  refreshTokenValiditySeconds?: number;
  requestObjectSigningAlg?: any;
  requestUris?: any[];
  requireAuthTime?: any;
  resourceIds?: any[];
  responseTypes: string[] = [];
  reuseRefreshToken?: boolean;
  scope?: string[];
  sectorIdentifierUri?: string;
  softwareId?: string;
  softwareStatement?: string;
  softwareVersion?: string;
  subjectType: string = 'PUBLIC';
  tokenEndpointAuthMethod?: string;
  tokenEndpointAuthSigningAlg: string = 'HS256';
  tosUri?: any;
  userInfoEncryptedResponseAlg?: any;
  userInfoEncryptedResponseEnc?: any;
  userInfoSignedResponseAlg?: any;
}

export declare type Clients = Client[];
